variables:
  - name: 'repositoryName' # Name of the repository
    value: 'AzureAD/microsoft-authentication-library-for-objc'

schedules:
# daily build will only be triggered if there is any change between the build and last successful build
- cron: "0 4 * * *"
  displayName: Daily 8 pm build
  branches:
    include:
    - dev
- cron: "0 20 * * 0"
  displayName: Weekly Sunday build
  branches:
    include:
    - dev
  always: true

trigger:
  branches:
      include:
      - release/*
      - hotfix/*

pr: none

pool:
  vmImage: 'macOS-13'

jobs:
- job: spm_test
  displayName: Run SPM integration test script
  timeoutInMinutes: 30
  cancelTimeoutInMinutes: 5
  workspace:
    clean: all
  
  steps:

  - checkout: self
    clean: true
    submodules: true
    fetchDepth: 1
    persistCredentials: true
    path: s

  - task: Bash@3
    displayName: Run SPM integration test script
    inputs:
      filePath: 'spm-integration-test.sh'